### ISSUE TITLE
Can the translation target language be changed?

### ISSUE THREAD

**Issue by wang19951120** [DinakiS/renpy-translate-utils#1]
For example, Chinese

**Comment by DinakiS** [comment]
You can pass the language in `generateFile` options.
`generator.generateFile(blocks, { language: 'chinese' });`
Checkout the this file https://github.com/DinakiS/renpy-translate-utils/blob/master/tests/test.js
Or you can change the language manually:
```
  const file = path.join(__dirname, 'simple.rpy');
  const blocks = await parser.parseFile(file);

  blocks.forEach(block => {
    block.meta.lang = 'chinese';
  })
```
